# This file describes the builds

# Builds for GitHub Actions
builds = [
    "bookworm-rt-am64xx-evm",
]

# List of all valid bookworm builds
[bookworm-rt-am64xx-evm]
    machine = "am64xx-evm"
    distro_codename = "bookworm"
    rt_linux = "true"