# This file describes the builds

# Builds for GitHub Actions
builds = [
    "am62p-bookworm-09.01.00.008",
    "am62-bookworm-09.01.00.008",
    "am62lp-bookworm-09.01.00.008",
    "am62sip-bookworm-09.01.00.008",
    "am64-bookworm-09.01.00.008",
]

# List of all valid builds
[am62p-bookworm-09.01.00.008]
    machine = "am62pxx-evm"
    bsp_version = "09.01.00.008"
    distro_variant = "am62p-bookworm"

[am62-bookworm-09.01.00.008]
    machine = "am62xx-evm"
    bsp_version = "09.01.00.008"
    distro_variant = "am62-bookworm"

[am62lp-bookworm-09.01.00.008]
    machine = "am62xx-lp-evm"
    bsp_version = "09.01.00.008"
    distro_variant = "am62-bookworm"

[am62sip-bookworm-09.01.00.008]
    machine = "am62xxsip-evm"
    bsp_version = "09.01.00.008"
    distro_variant = "am62sip-bookworm"

[am64-bookworm-09.01.00.008]
    machine = "am64xx-evm"
    bsp_version = "09.01.00.008"
    distro_variant = "am64-bookworm"

