---
mmdebstrap:
  architectures:
    - arm64
  mode: auto
  keyrings:
    - /usr/share/keyrings/debian-archive-keyring.gpg
  suite: bookworm
  variant: standard
  components:
    - main
    - contrib
    - non-free-firmware
  early-packages:
    - gnupg
  packages:
    - build-essential
    - gpg
    - curl
    - firmware-ti-connectivity
    - init
    - iproute2
    - less
    - libdrm-dev
    - libpam-systemd
    - locales
    - neofetch
    - network-manager
    - net-tools
    - openssh-server
    - sudo
    - vim
    - k3conf
    - weston
    - cryptodev-linux-dkms
    - firmware-ti-ipc-am64
    - firmware-cnm-wave
    - firmware-ti-prueth-am64
    - firmware-ti-pruhsr-am64
    - firmware-ti-prusw-am64
    - libti-rpmsg-char
    - libti-rpmsg-char-dev
    - libpru-pssp-dev
    - pru-pssp
    - parted
    - e2fsprogs
    # Pull RIAPS built Linux Kernel
    - linux-image-6.1.80-rt26-k3-rt-dirty=6.1.80-rt26-k3-rt-dirty-8
    - linux-headers-6.1.80-rt26-k3-rt-dirty=6.1.80-rt26-k3-rt-dirty-8
    - linux-libc-dev=6.1.80-rt26-k3-rt-dirty-8
    # RIAPS Platform Packages
    - apparmor
    - apparmor-profiles
    - apparmor-profiles-extra
    - apparmor-utils
    - apt-transport-https
    - autoconf
    - autogen
    - automake
    - avahi-utils
    - bison
    - byacc
    - can-utils
    - cargo
    - cmake
    - debconf-utils
    - flex
    - gpsd
    - git
    - gpiod
    - htop
    - ifupdown
    - iptables
    - libavl1
    - libargon2-0-dev
    - libasio-dev
    - libboost-dev
    - libcap-dev
    - libcurl4-gnutls-dev
    #- libcurl4-openssl-dev -- this package conflicts with libcurl4-gnutls-dev (needed for opendht)
    - libev4
    - libffi-dev
    - libgnutls30
    - libgnutls28-dev
    - libgpiod-dev
    - libhttp-parser-dev
    - libiio-utils
    - libjsoncpp-dev
    - liblz4-1
    - liblz4-dev
    - libmsgpackc2
    - libmsgpack-dev
    - libncurses5-dev
    - libpcap0.8
    - libpcap-dev
    - libpcre2-dev
    - libprotobuf32
    - libprotobuf-c1
    - libreadline-dev
    - libssh-4
    - libssh-dev
    - libssl3
    - libssl-dev
    - libsystemd-dev
    - libtool
    - libtool-bin
    - libuuid1
    - linuxptp
    - libzmq5
    - libzmq3-dev
    - make
    - nano
    - nettle-dev
    - openssl
    - pkg-config
    - pps-tools
    - python-is-python3
    - python3
    - python3-dev
    - python3-pip
    - python3-pkgconfig
    - python3-setuptools
    - python3-smbus
    - python3.11-venv
    - rdate
    - rsyslog
    - rustc
    - quota
    - software-properties-common
    - tmux
    - tree
    - uuid-dev
    - wget
  mirrors:
    - http://deb.debian.org/debian
  setup-hooks:
      # Setup TI Debian Package Repository
    - 'mkdir -p $1/etc/apt/sources.list.d/'
    - 'wget https://raw.githubusercontent.com/TexasInstruments/ti-debpkgs/main/ti-debpkgs.sources -P $1/etc/apt/sources.list.d/'
      # Setup Apt repository preferences
    - 'mkdir -p $1/etc/apt/preferences.d/'
    - 'printf "Package: *\nPin: origin TexasInstruments.github.io\nPin-Priority: 1001" >> $1/etc/apt/preferences.d/ti-debpkgs'
      # Prioritize customized Kernel for RIAPS
    - 'printf "Package: *\nPin: origin riaps.isis.vanderbilt.edu\nPin-Priority: 1050" >> $1/etc/apt/preferences.d/riaps-debpkgs'
      # Setup Kernel post-install scripts
    - 'mkdir -p $1/etc/kernel/postinst.d/'
    - 'echo "PWD = $PWD"'
    - 'upload target/kernel/postinst.d/cp-kernel-and-overlays /etc/kernel/postinst.d/cp-kernel-and-overlays'
    - 'chmod a+x $1/etc/kernel/postinst.d/cp-kernel-and-overlays'
      # Setup RIAPS Apt repository (custom kernel found here)
    - 'mkdir -p $1/tmp/riaps/'
    - 'mkdir -p $1/usr/share/keyrings/'
    - 'wget https://riaps.isis.vanderbilt.edu/keys/riapspublic.key -P $1/tmp/riaps'
    - 'gpg --dearmor $1/tmp/riaps/riapspublic.key'
    - 'mv $1/tmp/riaps/riapspublic.key.gpg $1/usr/share/keyrings/riaps-archive-keyring.gpg'
    - 'upload target/riaps/sysfiles/etc/apt/sources.list.d/riaps.list /etc/apt/sources.list.d/riaps.list'
      # Setup ZeroMQ Repo to get the draft APIs
    - 'wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-draft/Debian_12/Release.key -P $1/tmp/riaps'
    - 'gpg --dearmor $1/tmp/riaps/Release.key'
    - 'mv $1/tmp/riaps/Release.key.gpg $1/usr/share/keyrings/zeromq-archive-keyring.gpg'
    - 'upload target/riaps/sysfiles/etc/apt/sources.list.d/zeromq.list /etc/apt/sources.list.d/zeromq.list'
    - 'apt-get update'
  essential-hooks:
    # FIXME: Find a better workaround instead of sleep
    - 'sleep 10' # workaround for /proc resource busy unable to umount issue
  customize-hooks:
      # Remove passwd for root user
    - 'chroot "$1" passwd --delete root'
      # Fix apt install mandb permission issue
    - 'chroot "$1" chown -R man: /var/cache/man/'
    - 'chroot "$1" chmod -R 755 /var/cache/man/'
      # update packages to avoid mandatory update after first boot
    - 'chroot "$1" apt-get update'
      # Setup .bashrc for clean command-line experience
    - 'chroot "$1" cp /etc/skel/.bashrc ~/.bashrc'
      # Enable ssh to root user without password
    - 'chroot "$1" echo "PermitRootLogin yes" >> $1/etc/ssh/sshd_config'
    - 'chroot "$1" echo "PermitEmptyPasswords yes" >> $1/etc/ssh/sshd_config'
      # Resize Rootfs Service
    - 'chroot "$1" mkdir -p /usr/bin'
    - 'upload target/resize_rootfs/resize_rootfs.sh /usr/bin/resize_rootfs.sh'
    - 'chroot "$1" chmod a+x /usr/bin/resize_rootfs.sh'
    - 'chroot "$1" mkdir -p /etc/systemd/system/'
    - 'upload target/resize_rootfs/resize_rootfs.service /etc/systemd/system/resize_rootfs.service'
    - '$BDEBSTRAP_HOOKS/enable-units "$1" resize_rootfs'
      # Add RIAPS Specific Hooks
    - 'chroot "$1" mkdir -p /opt/riaps'
      # Setup place to pull out log files
    - 'mkdir -p /tmp-logs'
      # Upload system files
    - 'upload target/riaps/sysfiles/etc/sudoers.d/riaps /etc/sudoers.d/riaps'
    - 'upload target/riaps/sysfiles/etc/systemd/system/sethostname.service /etc/systemd/system/sethostname.service'
    - 'upload target/riaps/sysfiles/usr/bin/set_unique_hostname /usr/bin/set_unique_hostname'
    - 'chroot "$1" chmod +x /usr/bin/set_unique_hostname'
    - '$BDEBSTRAP_HOOKS/enable-units "$1" sethostname.service'
      # Setup RIAPS User
    - 'upload target/riaps/install_files/setup_riaps_user.sh /opt/riaps/setup_riaps_user.sh'
    - 'chroot "$1" chmod a+x /opt/riaps/setup_riaps_user.sh'
    - 'chroot "$1" /bin/bash -c "/opt/riaps/setup_riaps_user.sh" >"$1/opt/riaps/setup_riaps_user.log" 2>&1 || true'
    - 'cp $1/opt/riaps/setup_riaps_user.log $1/../../../logs/setup_riaps_user.log'
      # Update date
    - 'chroot "$1" rdate -n -4 time.nist.gov'
      # Setup Watchdog timer
    - 'chroot "$1" echo " " >> /etc/sysctl.conf'
    - 'chroot "$1" echo "###################################################################" >> /etc/sysctl.conf'
    - 'chroot "$1" echo "# Enable Watchdog Timer on Kernel Panic and Kernel Oops" >> /etc/sysctl.conf'
    - 'chroot "$1" echo "# Added for RIAPS Platform (01/25/18, MM)" >> /etc/sysctl.conf'
    - 'chroot "$1" echo "# Enable OOM-Killer" >> /etc/sysctl.conf'
    - 'chroot "$1" echo "# Added for RIAPS Platform (10/25/21, MM)" >> /etc/sysctl.conf'
    - 'chroot "$1" echo "kernel.panic_on_oops = 1" >> /etc/sysctl.conf'
    - 'chroot "$1" echo "kernel.panic = 5" >> /etc/sysctl.conf'
    - 'chroot "$1" echo "vm.oom-kill = 1" >> /etc/sysctl.conf'
    - 'upload target/riaps/sysfiles/etc/fstab /etc/fstab'
      # Install chrony
    - '$BDEBSTRAP_HOOKS/disable-units "$1" systemd-timesync.service'
    - 'chroot "$1" apt-get install chrony -y'
      # Build key libraries
    - 'upload target/riaps/install_files/external_build.sh /opt/riaps/external_build.sh'
    - 'upload target/riaps/install_files/python_installs.sh /opt/riaps/python_installs.sh'
    - 'chroot "$1" pip3 install Cython --break-system-packages --verbose'
    - 'chroot "$1" chmod a+x /opt/riaps/external_build.sh'
    - 'chroot "$1" /bin/bash -c "/opt/riaps/external_build.sh" >"$1/opt/riaps/external_build.log" 2>&1 || true'
    - 'cp $1/opt/riaps/external_build.log $1/../../../logs/external_build.log'
      # Setup TSN libraries
    - 'chroot "$1" apt-get remove libcurl4-gnutls-dev -y'
    - 'chroot "$1" apt-get install libcurl4-openssl-dev -y'
    - 'upload target/riaps/install_files/tsn_lib_build.sh /opt/riaps/tsn_lib_build.sh'
    - 'upload target/riaps/install_files/nw-configurator.c /opt/riaps/nw-configurator.c'
    - 'chroot "$1" chmod a+x /opt/riaps/tsn_lib_build.sh'
    - 'chroot "$1" /bin/bash -c "/opt/riaps/tsn_lib_build.sh" >"$1/opt/riaps/tsn_lib_build.log" 2>&1 || true'
    - 'cp $1/opt/riaps/tsn_lib_build.log $1/../../../logs/tsn_lib_build.log'
      # Upload sysrepod.service and netopeer2-serverd.service (both left disabled)
    - 'upload target/riaps/sysfiles/etc/systemd/system/sysrepod.service /etc/systemd/system/sysrepod.service'
    - 'upload target/riaps/sysfiles/etc/systemd/system/netopeer2-serverd.service /etc/systemd/system/netopeer2-serverd.service'
      # Add Yang Models
    - 'chroot "$1" mkdir -p /etc/sysrepo/data/notifications'
    - 'chroot "$1" mkdir -p /etc/sysrepo/yang'
    - 'chroot "$1" cp /usr/local/share/yang/modules/sysrepo/ietf-netconf-notifications.yang /etc/sysrepo/yang/ietf-netconf-notifications@2012-02-06.yang'
    - 'chroot "$1" cp /usr/local/share/yang/modules/sysrepo/ietf-netconf-with-defaults.yang /etc/sysrepo/yang/ietf-netconf-with-defaults@2011-06-01.yang'
    - 'chroot "$1" cp /usr/local/share/yang/modules/sysrepo/ietf-netconf.yang /etc/sysrepo/yang/ietf-netconf@2011-06-01.yang'
    - 'upload target/riaps/sysfiles/usr/local/share/netopeer2/setup.sh /usr/local/share/netopeer2/setup.sh'
    - 'chroot "$1" chmod a+x /usr/local/share/netopeer2/setup.sh'
      # Install python
    - 'chroot "$1" chmod a+x /opt/riaps/python_installs.sh'
    - 'chroot "$1" /bin/bash -c "/opt/riaps/python_installs.sh" >"$1/opt/riaps/python_installs.log" 2>&1 || true'
    - 'cp $1/opt/riaps/python_installs.log $1/../../../logs/python_installs.log' 
      # Set iptables to legacy version
    - 'chroot "$1" update-alternatives --set iptables /usr/sbin/iptables-legacy'
    - 'chroot "$1" update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy'
      # Install RIAPS packages
      # MM TODO: for now the correct riaps-pycom for the am64x is located in the VU box account
    #- 'chroot "$1" apt-get install riaps-pycom-am64x riaps-timesync-arm64'
    - 'chroot "$1" apt-get install riaps-timesync-arm64'
      # Set locale
    - 'upload target/riaps/install_files/locale_setup.sh /opt/riaps/locale_setup.sh'
    - 'chroot "$1" chmod a+x /opt/riaps/locale_setup.sh'
    - 'chroot "$1" /bin/bash -c "/opt/riaps/locale_setup.sh" >"$1/opt/riaps/locale_setup.log" 2>&1 || true'
    - 'cp $1/opt/riaps/locale_setup.log $1/../../../logs/locale_setup.log'
      # Remove packages and files used in image creation
    - 'chroot "$1" apt-get remove libboost-dev libcap-dev libffi-dev libgnutls28-dev libncurses5-dev libncurses-dev -y'
    - 'chroot "$1" apt-get remove libsystemd-dev libmsgpack-dev libpcap-dev uuid-dev liblz4-dev nettle-dev bison -y'
    - 'chroot "$1" apt-get remove libcurl4-gnutls-dev libasio-dev libargon2-0-dev libhttp-parser-dev libjsoncpp-dev libzmq3-dev -y'
    - 'chroot "$1" apt autoremove -y'
    - 'chroot "$1" pip3 uninstall --break-system-packages cython -y'
    - 'chroot "$1" rm -R /opt/riaps'

